[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
lib_deps =
    https://github.com/micro-ROS/micro_ros_arduino.git
    adafruit/Adafruit SSD1306
    adafruit/Adafruit GFX Library
    madhephaestus/ESP32Servo
    adafruit/Adafruit BusIO
    
