name: Build Alex Bot Firmware
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Setup PlatformIO
        run: pip install platformio

      - name: Build Firmware
        run: pio run -d .

      - name: Upload Binary
        uses: actions/upload-artifact@v4
        with:
          name: alex-bot-firmware
          path: .pio/build/esp32s3/firmware.bin
          
