name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Setup PlatformIO
        run: pip install platformio

      - name: Build
        # This tells PlatformIO to build using the config at root, 
        # but look in src/src for the code.
        run: pio run -d .
        
